### PR TITLE
moved to csproj and nestandard2

### PR DESCRIPTION
**Pull request by jchannon**
As the title suggests.

Had to rename the namespaces to make embedded resources working.

Tidied the solution structure
Tidied the repo structure
Edited README and added nuget link
Removed Samples folder

### CODE REVIEW

**Comment by igorshmukler** [comment]
Great job. I don't have netstandard2.2 SDK yet, so I tried with 2.1. Worked like a charm.

**Comment by jchannon** [comment]
That’s fine!

The library targets netstandard2.0 which can be consumed by any SDK that is 2.x

Glad it worked for you though!

Will work on fixing the TODO items and then we can get it merged and published for public consumption

--


On 12 July 2019 at 14:59:10, Igor Shmukler (notifications@github.com<mailto:notifications@github.com>) wrote:

Great job. I don't have netstandard2.2 SDK yet, so I tried with 2.1. Worked like a charm.

**Comment by jchannon** [comment]
Have pushed the changes. If you're happy, we can merge and I'll publish it

**Comment by igorshmukler** [comment]
I am not certain whether we needed to drop samples. Yet, I don't have strong feelings either way. While I was building the original LdapHelper class, I used samples as references and even added samples for specific search cases e.g. VLV to the existing set.
At the same time, all the original samples are still available from within the `master` branch. This is more of a philosophical approach question...

As far as the PR/code-change itself, looks great. I think that we should go ahead and merge it.

**Pull request merged**
