### PR TITLE
[WIP] Make CoreCLR compatible

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by igorshmukler** [comment]
@jchannon glanced at the commit. it looks good. yet, since you changed strings conversion routines and dumped some [empty] methods, i normally would prefer not to merge without testing the library. i actually fixed critical bugs in the string conversion routines in this library, in the past.

hence, a few questions:
1. what do you think about me reviewing/testing this properly? are you totally confident that the bugs could be introduced this this one?
2. does this thing still builds with older Visual Studio and XamarinStudio?

**Comment by jchannon** [comment]
Hi @igorshmukler 

As you may/may not know at VQ we are moving everything to CoreCLR and this lib needs converting.

Some things are no longer present in CoreCLR like ISerializeable, ICloneable.

It won't work with anything older than VS2015 however that may change when MS fix the csproj tooling for CoreCLR.

This PR will need a thorough testing due to the large changes.

This should not be merged until all at VQ agree it's ready

**Comment by igorshmukler** [comment]
@jchannon
Mike mentioned that we are moving to CoreCLR.
I get the removed classes. Nor have any specific problem with your commit. Personally, since your code does not build with most tools, I would make a new branch and leave the master alone, for now.
Either way, understood that proper testing is needed. That was my main question.

**Comment by igorshmukler** [comment]
Sorry, you did make a new branch. My bad.

**Pull request closed without merging**
